### ISSUE TITLE
Is there a license for the map data?

### ISSUE THREAD

**Issue by voneiden** [saik0/Leaflet.KSP#7]
Hi saik0,

not really an issue in itself, but I was wondering if the map data at http://www.kerbalmaps.com/ is available for use in other projects, and if yes, what would the license for it be?

Thanks & regards,
Matti

**Comment by saik0** [comment]
@voneiden

That's a great question, and I doubt I  will be able to answer satisfactorily. I am not a lawyer, this is not legal advice. 

If I had to guess I'd say that in the US the map data would be [fair use](http://en.m.wikipedia.org/wiki/Fair_use]). Squad is a Mexico based company though, and I'm not sure what effect that has.

If I could say with certainty that I had a claim to the copyright I would have published it under (creative commons by-nc-sa)[ http://creativecommons.org/licenses/by-nc-sa/2.0/]

I hope that helps. Out of curiosity what do you want to do with the map data?

**Comment by voneiden** [comment]
Alrighty, that does help, thanks. Currently using/experimenting them as a base for displaying groundtrack map ( http://i.imgur.com/8Mn8nzg.png ), but I haven't pushed them to the repo obviously so far. I'm also undecided whether to stick with the lower quality hand drawn green maps or use the actual maps from your site. Project repository is here: https://github.com/voneiden/ksp-missioncontrol/
